### ISSUE TITLE
Display statistics at URL

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-live-changes-config#1]
Hello,
First, congratulations for this new project which look promising and will be a great addition to JMeter.

What do you think of adding equivalent of Summary statistics while test is running ?

**Comment by delirius325** [comment]
Hi!

First and foremost, thanks a lot!

Now as for the statistics summary, I find that this could be a wonderful idea. This could give people a good idea of how their test is running without having to send data to an external source like Influx, ES, etc.

I'll definitely look into it!

**Comment by Kitty2014** [comment]
👍 @pmouawad @delirius325 did you used wechat [,](https://web.wechat.com/) we can Pull group group small group real-time discussion

**Comment by delirius325** [comment]
@Kitty2014 I'm more of a Slack kind of guy, but I believe (for now at least) that the GitHub issue system works well. With the different timezones it's tough to always be in sync for "real-time discussions" to work anyways. I'm in North America, I know @pmouawad is in Europe so there is already a 6 hours gap.
