### ISSUE TITLE
Verify the standard deviation & percentiles calculation

### ISSUE THREAD

**Issue by delirius325** [delirius325/jmeter-live-changes-config#10]
Verify that the standard deviation & 90th percentile calculations are the correct one.

__*The code snippets are scrollable*__

# Standard deviation
https://github.com/delirius325/jmeter-live-changes-config/blob/087b29e92d5e6bbaf021831a24fd75d218128fd5/src/main/java/io/github/delirius325/jmeter/config/livechanges/ResultHolder.java#L45-L66

# 90th percentile
https://github.com/delirius325/jmeter-live-changes-config/blob/087b29e92d5e6bbaf021831a24fd75d218128fd5/src/main/java/io/github/delirius325/jmeter/config/livechanges/ResultHolder.java#L68-L83

**Comment by delirius325** [comment]
@pmouawad Would it be possible for you to review this?

Thanks,

**Comment by pmouawad** [comment]
Hello,
Use latencyutils or hdrhistogram or even better micrometer.
Your best option is to make it generic and contribute it to core so you can reuse it here and in other plugins.
