### ISSUE TITLE
how to chang the LiveChanges

### ISSUE THREAD

**Issue by Kitty2014** [delirius325/jmeter-live-changes-config#12]
<img width="1150" alt="conf" src="https://user-images.githubusercontent.com/7512412/54938839-248b2980-4f62-11e9-860f-eed771c80dda.png">
dear author,
how can i change with postman or other tools to see the rest API which change in config
any demo jmx or detail ?

**Comment by delirius325** [comment]
Hi @Kitty2014 ,

To be able to connect to the API, the test needs to be running. The whole point is to start the server when the test starts.

To see an extended list of all the available API endpoints, I suggest you read the README section of the repository.

Thanks,
