### ISSUE TITLE
Not able add threads to the thread group and miscount number of threads

### ISSUE THREAD

**Issue by QAInsights** [delirius325/jmeter-live-changes-config#22]
I have followed the below steps to add more number of threads. But the thread count is increasing for the very first time. If we inject the thread second time, it is not working.

1. Run the script with one thread
2. Add threads e.g. `5`
3. Thread count is increased to 5. (it is also a bug, the count should be 6)
4. Add 5 threads again
5. Thread count is still showing 5 even after waiting.

Here is the recording:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/z7ukKHs8vbc/0.jpg)](https://www.youtube.com/watch?v=z7ukKHs8vbc)

**Comment by delirius325** [comment]
Yeah.. Thanks for confirming this; it's related to issue #18.

I'm actively working on this, hopefully I'm able to come up with a fix tomorrow.

**Comment by delirius325** [comment]
Closing because it's related to #18
