### ISSUE TITLE
Add Access-Control-Allow-Origin response header response 

### ISSUE THREAD

**Issue by QAInsights** [delirius325/jmeter-live-changes-config#23]
Could you please add `Access-Control-Allow-Origin` response header to allow CORS? This will help in StopLight to get the response, else it will throw the error.

![image](https://user-images.githubusercontent.com/2826376/83547615-803f3400-a4d0-11ea-9ed8-fdaf53c47efd.png)

**Comment by delirius325** [comment]
Closing since we're using Swagger instead of Stoplight.
