### ISSUE TITLE
Changing variables does not have a sense at global level

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-live-changes-config#3]
As you know variables are related to a Thread, I don't see how changing variables could work.

Or are you limiting this feature to "global" variables ?

**Comment by delirius325** [comment]
Yeah so right now, the plugin only works with one `Thread Group` (as mentioned in the README), I'm trying to figure out a way to be able to query each separate thread group to be able to change the variables and inform every thread in the thread group.

Now that being said, I'm not sure if that's even possible - although I'm looking into it.

**Comment by Kitty2014** [comment]
@delirius325  could you write some demo jmx config with your  plugin and upload googleDrive, we can  used it to debug
We can analyze the new ideas of sharing research together.

**Comment by delirius325** [comment]
Hi @Kitty2014 ,

I've updated the setup section of the README with version 0.0.2. Adding the Live Changes config element is fairly simple. All you have to do is add the element at the root of your Test Plan.

For further help on this, please refer to the [README](https://github.com/delirius325/jmeter-live-changes-config/blob/master/README.md) or create a new issue.

Thank you,

**Comment by delirius325** [comment]
For the time being, changing variables will only be available at a `User defined` (`Test Plan`) level. We might find a way to modify and propagate variables changes to threads in the future, but it is not the goal for now.

This issue is now closed.
