### ISSUE TITLE
Adding threads

### ISSUE THREAD

**Issue by pmouawad** [delirius325/jmeter-live-changes-config#4]
Hello,
Looking at code of LiveChanges#checkForThreadChanges , I think there would be an issue in doing:

`threadGroup.addNewThread(0, new StandardJMeterEngine());`

You would end up with multiple engines which is unexpected.

I understand why you did that, I see there is no access to StandardEngine in core JMeter nor simple method for adding threads.

Maybe it's worth enhancement request.

**Comment by delirius325** [comment]
Indeed, I did it because I really didn't have any choice. I'll make the enhancement request (and who knows, maybe just commit it myself 🤣). 

Again, thanks for the feedback!

**Comment by delirius325** [comment]
Fixed this by using `JMeterContextService.getContext().getEngine()`
